### ISSUE TITLE
[feature] Exam results (semester, overall)

### ISSUE THREAD

**Issue by ditsuke** [ditsuke/go-amizone#36]
## Requirements

- Expose overall results (cumulative-gpa)
- Expose semester-wise results (sgpa, course metrics like grade, grade point, credits)

## Extra info

On the portal, this information is available at `Examination` > `Examination Result` from the sidebar. For semester-wise results, there's a dropdown that lets you navigate to any semester for which the result has been declared (the default is the last-declared semester).

**Comment by Blonteractor** [comment]
Working on this
