### ISSUE TITLE
Faculty Feedback not submitting 

### ISSUE THREAD

**Issue by typhoon11** [ditsuke/go-amizone#49]
When trying to submit the faculty feedback using the public API it's not working and always gives an error. Screenshot attached below
![image](https://github.com/ditsuke/go-amizone/assets/66431066/c487fbd4-2088-436e-aedc-a49ffecab19f)

**Comment by ditsuke** [comment]
Hi @typhoon11, was this issue resolved? Could you please share what was going wrong?

**Comment by typhoon11** [comment]
> Hi @typhoon11, was this issue resolved? Could you please share what was going wrong?

Yes it was resolved the documented way in the Postman collection was wrong for the API. In postman the the field were used in query params but according to code it should be in body. The Postman Collection need to be updated

**Comment by ditsuke** [comment]
> > Hi @typhoon11, was this issue resolved? Could you please share what was going wrong?
> 
> Yes it was resolved the documented way in the Postman collection was wrong for the API. In postman the the field were used in query params but according to code it should be in body. The Postman Collection need to be updated

Thanks for reporting. I've addressed the issue with the collection.
